import Head from 'next/head'
import { SearchLine } from '@/components/header/SearchLine'
import { Heading } from '@/components/header/Heading'
import { Footer } from '@/components/Footer'
import { UsersList } from '@/components/UsersList'
import { IUser } from '@/types'
import useSWR from 'swr'
import { fetcher } from './api/hello'
import { useGetEmail } from '@/hooks'
import Loader from '@/components/ui/Loader/Loader'
import styles from '@/styles/accounts.module.scss'

export default function Accounts() {
  const {data, error} = useSWR<IUser[] | undefined>('https://frontend-test-api.yoldi.agency/api/user', fetcher)
  const email = useGetEmail()
  const myUser: IUser | undefined = data?.find((user) => user.email === email)
  if(!data) {
    return (
      <Loader />
    )
  }
  return (
    <>
      <Head>
        <title>Yoldi accounts list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.wrapper}>
        <header>
          <SearchLine />
          <Heading />
        </header>
        <main className={styles.main}>
          <div className={styles.container}>
            <UsersList myUser={myUser} userList={data} />
          </div>
        </main>
        {!email ? <Footer /> : null} 
      </div>
    </>
  )
}