import Head from 'next/head'
import { SearchLine } from '@/components/header/SearchLine'
import { Heading } from '@/components/header/Heading'
import { useEffect, useState } from 'react'
import { Footer } from '@/components/Footer'
import { UsersList } from '@/components/UsersList'
import { IUser } from '@/types'
import useSWR from 'swr'
export default function Home() {
  return (
    <>
      <Head>
        <title>Yoldi accounts list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
    </>
  )
}
