import Head from 'next/head'
import { SearchLine } from '@/components/header/SearchLine'
import { Heading } from '@/components/header/Heading'
import { Footer } from '@/components/Footer'
import { LoginForm } from '@/components/LoginForm'
import styles from '@/styles/register.module.scss'

export default function Login() {
  return (
    <>
      <Head>
        <title>Yoldi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.wrapper}>
        <header>
          <SearchLine />
          <Heading user={true} />
        </header>
        <main className={styles.main}>
          <div className={styles.container}>
            <LoginForm />
          </div>
        </main>
        <Footer />
      </div>
    </>
  )
}