import Head from 'next/head'
import { SearchLine } from '@/components/header/SearchLine'
import { Heading } from '@/components/header/Heading'
import { Footer } from '@/components/Footer'
import styles from '@/styles/register.module.scss'
import { RegistrForm } from '@/components/RegistrForm'

export default function Register() {
  return (
    <>
      <Head>
        <title>Yoldi register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.wrapper}>
        <header>
          <SearchLine />
          <Heading />
        </header>
        <main className={styles.main}>
          <div className={styles.container}>
            <RegistrForm />
          </div>
        </main>
        <Footer />
      </div>
    </>
  )
}