import Head from 'next/head'
import { SearchLine } from '@/components/header/SearchLine'
import { Heading } from '@/components/header/Heading'
import { Footer } from '@/components/Footer'
import { RegistrForm } from '@/components/RegistrForm'
import styles from '@/styles/register.module.scss'
import { useState } from 'react'
import Loader from '@/components/ui/Loader/Loader'

export default function Register() {
  const [loading, setLoading] = useState<boolean>(false)
  return (
    <>
      <Head>
        <title>Yoldi register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.wrapper}>
        <header>
          <SearchLine />
          <Heading />
        </header>
        <main className={styles.main}>
          {loading && <Loader />}
          <div className={styles.container}>
            <RegistrForm setLoading={setLoading}/>
          </div>
        </main>
        <Footer />
      </div>
    </>
  )
}