// import Head from 'next/head'
// import { SearchLine } from '@/components/header/SearchLine'
// import { Heading } from '@/components/header/Heading'
// import { useEffect, useState } from 'react'
// import { Footer } from '@/components/Footer'
// import axios from 'axios'
// import { UsersList } from '@/components/UsersList'
// import styles from '@/styles/accounts.module.scss'
// import { IUser } from '@/types'
// import { useGetEmail } from '@/hooks'

// export default function User() {
//   const [userList, setUserList] = useState<IUser[] | undefined>()
//   const email = useGetEmail()

//   if(email) {
//     const getUser = async () => {
//       try {
//         const response = await axios.get(`https://frontend-test-api.yoldi.agency/api/user${localStorage.getItem('email')}`)
//           setUserList(response.data)
//           console.log(response.data)
//         } catch (error) {
//           console.log(error)
//         }
//     }
//     getUser()
//   }
  
//   return (
//     <>
//       <Head>
//         <title>Yoldi accounts list</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//       </Head>
//       <div className={styles.wrapper}>
//         <header>
//           <SearchLine />
//           <Heading />
//         </header>
//         <main className={styles.main}>
//           <div className={styles.container}>
//             <UsersList userList={userList} />
//           </div>
//         </main>
//         {!email ? <Footer /> : null} 
//       </div>
//     </>
//   )
// }