import Head from 'next/head'
import { SearchLine } from '@/components/header/SearchLine'
import { Heading } from '@/components/header/Heading'
import { useEffect, useState } from 'react'
import { IUser } from '@/types'
import { AboutUser } from '@/components/AboutUser'
import { useRouter } from 'next/router'
import { fetcher } from '../../api/hello'
import useSWR from 'swr'
import styles from '../account.module.scss'
import { useGetEmail } from '@/hooks'
import Loader from '@/components/ui/Loader/Loader'

export default function AboutGuest() {
  const {data, error} = useSWR<IUser[] | undefined>('https://frontend-test-api.yoldi.agency/api/user', fetcher)
  const router = useRouter()
  const id = String(router.query.id).substring(0, String(router.query.id).length - 1)
  const guestUser: IUser | undefined = data?.find((user) => user.email == id)
  const email = useGetEmail()
  const myUser: IUser | undefined = data?.find((user) => user.email == email)
  
  if(!data || !myUser) {
    return (
      <Loader />
    )
  }
  return (
    <>
      <Head>
        <title>Yoldi user</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <header>
        <SearchLine />
        <Heading myUser={myUser}/>
      </header>
      <main className={styles.main}>
        <div className={styles.main__back} />
        <div className={styles.container}>
          <AboutUser myUser={guestUser} />
        </div>
      </main>
    </>
  )
}